[package]
name = "kitbag"
version = "0.1.0"
authors = ["Isaac Clayton <slightknack@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rmp-serde = "0.14"
# typetag = "0.1"
rand = "0.7"
sha3 = "0.9"
