[package]
name = "kitbag"
version = "0.1.0"
authors = ["Isaac Clayton <slightknack@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
# use message pack instead?
serde_cbor = "0.10"
rand = "0.7"
chacha20poly1305 = "0.7"
sha3 = "0.9"
